# conda tensoflow 설치

In [ ]:
# conda deactivate

# conda create --name tf tensorflow-gpu
# conda activate tf
# conda install jupyter
# jupyter notebook

In [1]:
import numpy as np
import tensorflow as tf

In [3]:
# conda list # gpu 설치

# numpy shape : (4,) -1차원 원소 4개 , (2,3)- 2차원 axis0=2, axis1=3, (4,3,2)

In [6]:
a = np.array([
    [2.1, 3.1, 3.9],
    [3.2, 4.5, 3.1]
])

In [7]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [8]:
np.mean(a, axis=0)

array([2.65, 3.8 , 3.5 ])

In [9]:
np.mean(a, axis=1)

array([3.03333333, 3.6       ])

In [10]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

# numpy에서 data type, axis에 대해 restrict

# tensor : data structre, data array, generalization

In [ ]:
# data :

# features : x1^2, x1*x2, sin(x) 같은 축

# layers: 
    
# epoch : 메모리에 다 안올라가서, 데이터로 다 돌아가게 하는것. 1회 시도
#         미니배치 사이즈를 얼마나 올릴 수 있냐?
#         배치사이즈 : 보통 이진수로 표기 gpu 코어가 2진수에 맞춰서 들어가야 해서
        
            
# training loss:0으로 수렴해야
    
# test loss:
    
# learning rate:
# activation:
# regularization:

In [ ]:
# api 자주 참조

In [ ]:
# 그래프 프레임 워크,

# 그래프를 그리는 것과 그래프를 실제로 돌리는 것은 별개 (tensor가 흐르게)


In [31]:
import tensorflow as tf

a=tf.constant(3, dtype=tf.float32, name='const') # a라는 변수에 저장돼있고 그래프를 그림
b=tf.Variable(0, dtype=tf.float32)
# c=a+b
# b=a+b
c=tf.assign(b, a+b) #라는 함수를 사용해야 함 원래 의도는 b=a+b
print(a)
print(b)
# print(c)

init = tf.global_variables_initializer() #변수 초기화 필요

# b= a+b 같은 식으로 활용 하려고


# with tf.name_scope('abc'):
#     a=tf.constant(3, dtype=tf.float32, name='const') # a라는 변수에 저장돼있고 그래프를 그림
# print(a)
# b=tf.constant(3)
# print(b)
# c=tf.constant(3, dtype=tf.float32) #같은 이름을 가진 tensor를 만들지 않으려고 1씩 증가
# print(c)

#값이 아직 없음, 위에서는 아무 것도 하지 않음

Tensor("const_15:0", shape=(), dtype=float32)
<tf.Variable 'Variable_3:0' shape=() dtype=float32_ref>


In [ ]:
# tf.get_variable('Const') #변수 이름으로 부를 때

In [17]:
with tf.Session() as sess:
    print(sess.run(a))
#a를 실제로 run해서 값을 나타냄

3.0


In [23]:
with tf.Session() as sess:
    sess.run(init)
    print(a+b) #아무 것도 없는 tensor가 출력 됨
#     print(sess.run(a+b)) # a+b는 문제 있는 텐서플로 코딩
#그래프를 그리는 행위를 세션 안에서 하면 안됨
#a+b라는 것도 그래프를 그림

Tensor("add_3:0", shape=(), dtype=float32)


In [25]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c)) 
    
#c=a+b를 미리 선언하고, c를 run해야 맞는 코딩


3.0


In [33]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    print(sess.run(b))

0.0
0.0


In [32]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(sess.run(c))

3.0
6.0


# Place Holder

In [54]:
np.random.seed(42) #보통은 seed 고정, 재현을 위해서
x = tf.placeholder(tf.float32, shape=(), name='x')
y = tf.placeholder(tf.float32, shape=(), name='y')
w = tf.Variable(np.random.randn(), dtype=tf.float32)

a = tf.assign(w, w + x + y)

init = tf.global_variables_initializer()

In [55]:
with tf.Session() as sess:
    sess.run(init)
    
    for _ in range(0, 10):
        print(sess.run(w))
        sess.run(a, feed_dict={x:1.0, y:2.0})
    print(sess.run(w))

0.49671414
3.496714
6.496714
9.496714
12.496714
15.496714
18.496714
21.496714
24.496714
27.496714
30.496714


In [ ]:
# Placeholder
# 그래프로 텐서를 입력하는 객체
# 학습하는 과정에서 값을 입력

In [ ]:
# variable
# 처음 초기화하고 그래프 연산에 의해서 값이 바뀌는 객체